modules/twinkleclose.js
https://zh.wikipedia.org/w/index.php?title=Template:TalkendH&diff=59686615&oldid=54545169
=> close: Add twv to Twinkle.close.codes

modules/twinkleclose.js
=> close: Enable tk option for non-admins

modules/friendlytag.js
=> tag: Resolve redirects for templates name

modules/twinklefluff.js
=> fluff: Hide customRevertSummary dropdown when it's empty

modules/twinkleblock.js
https://github.com/azatoth/twinkle/commit/5e1b167000c5e67d0b13f55a6429391d9abda1d4
檢查封禁衝突。
=> block: 檢查封禁衝突

modules/twinkleblock.js
=> block: Fix block info query params for ip range

morebits.css, morebits.js
https://github.com/azatoth/twinkle/commit/d57b85ea627c0f9e87dad51f3796e56f10cce7eb
目前：
更新後：
=> morebits: 在視窗標題使用預設顏色

morebits.js
https://github.com/azatoth/twinkle/commit/200c57651c00306edafbe3bc01eb69277190bf9f
https://github.com/azatoth/twinkle/commit/ffe5bbed292b9b1f5ffbe5ce57deb5604d674863
例如這樣就可以在歷史頁面進行巡查。
=> morebits: 當巡查連結不可用時，使用API從RC查詢必要參數

modules/twinkleconfig.js, modules/twinklexfd.js, twinkle.js
Fixes #46 
FYI: [AF records](https://zh.wikipedia.org/w/index.php?title=Special:%E6%BB%A5%E7%94%A8%E6%97%A5%E5%BF%97&wpSearchFilter=250)
=> xfd: Add XfD log, parallel to CSD

modules/twinkleblock.js
=> block: change the summary used in sending notice

morebits.js
=> morebits.js: Fix redirect checking regex

modules/twinklearv.js
=> arv: 修復VIP留言空行問題

modules/twinklespeedy.js
=> speedy: adjust the style to enlarge g11 criterion

modules/twinkleconfig.js, modules/twinklestub.js, twinkle.js
=> stub: add support to mark the page as patrolled

modules/twinklebatchdelete.js, modules/twinklefluff.js, modules/twinkleunlink.js
https://github.com/azatoth/twinkle/commit/cc3253026b08d6354896716adff0648c295c4c57
**注意：部署前記得將`mediawiki.language`加入依賴項**
=> Pass numbers through convertNumber

morebits.js, twinkle.js
https://github.com/azatoth/twinkle/commit/d81d9575d08b7cf89e208ba40f0fc4213ca8235a
=> Remove useragent 2.0 specification

modules/twinkleblock.js
https://github.com/azatoth/twinkle/commit/0714cbc30f4ad6158f5037e8bae34f0581d2a77d
=> block: better detect bots and turn off autoblock

modules/twinklecopyvio.js, modules/twinkleimage.js, modules/twinklespeedy.js, modules/twinklexfd.js, morebits.js
https://github.com/azatoth/twinkle/commit/b48f48eb22bf8ffd383b5ee2172bfcb91d375e5d
https://github.com/azatoth/twinkle/commit/b658e689172f803fdb7813bbc3dc538404699f5c
=> deletion modules: Don't follow cross-ns redirect while notifying user

modules/twinkleconfig.js, modules/twinklefluff.js, twinkle.js
Fixes #72 
Add config: `rollbackInPlace`
Remove config: `rollbackInCurrentWindow`
=> fluff: Unify link creation functions, add rollbackInPlace option for Contribs/RC

morebits.js
=> morebits.wiki.api: enable promise support

modules/twinkleimage.js
Fixes #67 
Currently waiting for local [no source no license template](https://en.wikipedia.org/wiki/Template:Di-no_source_no_license-notice)
=> image: use accurate template to notify users

modules/twinklefluff.js
https://github.com/azatoth/twinkle/commit/1b5e517fae5e13cb2b544a0d755224f4016935c6
Close #93
=> fluff: Don't add restoreThisRevision links to revdel'd history revisions

modules/twinklebatchdelete.js, modules/twinklebatchundelete.js, modules/twinkleconfig.js, twinkle.js
https://github.com/azatoth/twinkle/commit/ce8c8903a05de59c49d5cbd09c592380f6461cde
=> Merge individual chunk prefs into one: batchChunks

modules/twinkleunlink.js
https://github.com/azatoth/twinkle/commit/df6fb28ff53fd53e696f764752f30dbe03e6e6a1
順便把讀取輸入資料改成新版方式（`Morebits.quickForm.getInputData`）
=> unlink: Alert/return if no pages selected, show more accurate interface message

modules/twinkleclose.js
=> close: delete talkpage and redirects when deleting

modules/twinklewarn.js
=> warn: Don't follow cross-namespace redirects out of usertalk space

modules/twinklestub.js
=> stub: make custom templates above others

modules/friendlyshared.js, modules/friendlytag.js, modules/friendlytalkback.js, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleclose.js, modules/twinkleconfig.js, modules/twinklecopyvio.js, modules/twinklediff.js, modules/twinklefluff.js, modules/twinkleimage.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinklestub.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js
https://github.com/azatoth/twinkle/commit/8b211b116b4f91b4ff242fa4d57ae58fb0f1a1b8
=> Fix testing, move addInitCallback below callback definitions

morebits.js
https://github.com/azatoth/twinkle/commit/3369e92652919087c0600b2c2c60aaaa0a59c1c5
=> morebits: array: use better/more efficient implementations

modules/twinklebatchdelete.js, modules/twinklebatchundelete.js, modules/twinkleunlink.js, morebits.js
https://github.com/azatoth/twinkle/commit/33b5f7d790c8bd37860919fb267a526317790f86
=> morebits: integrate checkboxShiftClickSupport into quickForm

modules/friendlytag.js, modules/twinkleconfig.js, twinkle.js
https://github.com/azatoth/twinkle/blob/c338c26cc33ab12df0795465ac236d330f1c3a50/modules/friendlytag.js
=> tag: Merge from upstream

modules/twinklefluff.js
https://github.com/azatoth/twinkle/commit/11f3556bd603f68d10c112d54832a313417675b6
=> fluff: Fail nicely on and don't reveal revdel'd usernames

modules/twinklefluff.js, modules/twinklewarn.js
https://github.com/azatoth/twinkle/commit/941e281f491511470aceec00a2e9bd904c3a5068
warn: Don't insert twinkle-warn-warning-message before render
https://github.com/azatoth/twinkle/commit/2b6f9a76a2cff95dd9d33c26a9beae416f318357
=> fluff/warn: Pass timestamp from fluff to warn, allow skipping stale API check

morebits.js
發現「加入支援的標記入已存在的{{multiple issues}}」會卡住，請看上游報告  https://github.com/azatoth/twinkle/issues/1058
=> morebits: Fix insertAfterTemplates param checks

modules/friendlytag.js, modules/twinkleconfig.js, twinkle.js
Reverts Xi-Plus/twinkle#121
有不少Bug在部署後才發現
=> Revert "tag: Merge from upstream"

modules/twinkleprotect.js
https://github.com/azatoth/twinkle/commit/6b4ac03b68557e2bb24016857ece111945c7dec8
順便轉換成使用 getInputData
不過本地不會有 movelevel 為空的清況，為了之後合併方便就先留著
=> protect: Ensure a valid type of move protection

.gitignore, package.json, patch-test.js
https://github.com/azatoth/twinkle/commit/5fa322fb55c9b78c9ee1989761e120457a18f9a3
=> add script for easily creating localhost test loaders

modules/twinkleprotect.js
[錯誤範例](https://zh.wikipedia.org/w/index.php?title=Category%3A有存档的讨论页&diff=60913458&oldid=60913455)
=> protect: Fix expiry paramenter infinity checking

maintenance/i18n.py, modules/friendlytag.js, modules/twinklebatchdelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinklefluff.js, modules/twinklespeedy.js, modules/twinkleunlink.js, modules/twinklewarn.js, morebits.js
1. 由程式自動移除兩個參數相同的wgULS。
2. 重新產生所有介面訊息，實際有修改到的有：
1. block L457
2. fluff L694
3. warn L2427
Close #140
=> i18n: Remove useless wgULS and add some rules

modules/twinklewarn.js
1. 還原在 7c8fa51c4005800d9dcdcf9636b7b0a45d12b089 移除的main_flow函數
2. 在Flow上顯示autolevel不支援的警告訊息，並強制選取另一個模板
=> warn: Fix warning on flow pages

modules/twinkleconfig.js
https://github.com/azatoth/twinkle/commit/3354bd7a33e517acc4b027a0144b54710697a0a5
=> config: Remove obsolete torev option from openTalkPage

.gitignore, maintenance/get_templates.py, maintenance/tag_name.py, maintenance/util.py, modules/friendlytag.js, modules/twinkleblock.js, modules/twinkleclose.js
=> Add script to check {{Twinkle standard installation}} marking

modules/twinkleprotect.js
修復某些保護理由無法自動填入過期參數的Bug
{{RFPP}}參數已在站內完成適配調整
=> protect: Fix expiry filling for some templates

morebits.css
https://github.com/azatoth/twinkle/commit/b5c4fe5fbc11d33fcc54afbe33515b84ddc385cf
=> Bump font size to 12px

modules/twinkleblock.js, modules/twinkleprotect.js
從未保護：
> 目前保護：**無**
目前無保護，但曾保護：
> 目前保護：**無**
> 先前保護：在**TIME**被USER保護：**編輯：僅管理員**（無限期）**移動：僅管理員**（無限期）：查看**保護日誌**
目前被保護：
> 目前被**USER**保護：**編輯：僅管理員**（無限期）**移動：僅管理員**（無限期）：**保護日誌**
=> Display the detail of previous operation in window

modules/twinklewarn.js
=> warn: Fix bug on flow and update summary

modules/twinklewarn.js
=> warn: Fix previewing on flow

modules/twinkleprotect.js
https://github.com/azatoth/twinkle/commit/d3b6acfb5cc730ad9252588b6a1698309d2e403f
=> protect: Allow presets to override protection length

modules/twinklefluff.js
https://github.com/azatoth/twinkle/commit/ac876c2b3c60021891450ae8b6da10b938c65082
=> fluff: Revert multiple hidden revisions in a row

modules/twinkleprotect.js
https://github.com/azatoth/twinkle/commit/72e0b110826ef089a2899f40e54456860296d683
=> protect: Consolidate duplicate lists, filter out improper options

modules/twinklexfd.js
修復提刪中合併操作的使用者空間日誌文字，在[WT:TW](https://zh.wikipedia.org/w/index.php?oldid=61383866#AFD日志记录合并操作时有bug)上報告。
=> xfd: Fix user log text for merge

modules/twinklearv.js, modules/twinkleprotect.js, morebits.js
https://github.com/azatoth/twinkle/commit/76a047f73358e6da2d56913889227a9123212c3b
=> morebits: Deprecate RegExp.escape in favor of Morebits.string.escapeRegExp

modules/friendlyshared.js, modules/friendlytag.js, modules/friendlytalkback.js, modules/friendlywelcome.js, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleclose.js, modules/twinkleconfig.js, modules/twinklecopyvio.js, modules/twinklefluff.js, modules/twinkleimage.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinklestub.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js, twinkle.js
https://github.com/azatoth/twinkle/commit/7478ed212858a4193fd86b4a5a5b2feb94e98647
=> Add support for change tags, remove `summaryAd`

maintenance/i18n.py, modules/friendlytag.js, modules/friendlytalkback.js, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkleimage.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js
=> Update interface messages

modules/twinklefluff.js
=> fluff: Update confirmation message for rollbacking bot's edit

morebits.css
https://github.com/azatoth/twinkle/commit/399f1f881d0e8cd4a5db4880d1fa2b45c8a0d96f
=> morebits.css: make font sizes consistent across skins, browser settings

modules/friendlytag.js, modules/twinklecopyvio.js, modules/twinkleimage.js, modules/twinklespeedy.js, modules/twinklestub.js, modules/twinkleunlink.js, modules/twinklexfd.js, morebits.js
更新morebits.js到最新版本以繼續合併其他檔案的新修改。
=> Upgrade morebits

modules/twinkleunlink.js, twinkle.js
https://github.com/wikimedia-gadgets/twinkle/commit/8380ef0c2850d1fbdadcbdd8707e7aa72b3ec2cd
https://github.com/wikimedia-gadgets/twinkle/commit/a0c80063292650e2d13fd4953697a96df7f870d9
=> unlink: Fix api handing

modules/twinkleblock.js
=> block: display last block detail of expiring

modules/twinkleblock.js
1. 將標記功能改成可以選擇多個模板
2. 增加{{Locked global account}}
3. 其他模板增加常用參數選項
4. 微調tag/protect間的運作
=> block: Refactor tagging

modules/twinkleblock.js
1. {{uw-block1}}和{{uw-block2}}已重定向到{{uw-block}}，{{uw-block3}}已重定向到{{uw-blockindef}}。
2. {{uw-bblock}}沒使用到，移除。
=> block: Rename block1/2/3

modules/friendlytag.js
自[站内请求](https://zh.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=65665661#%E5%8A%A0%E5%85%A5%E6%96%B0%E5%8F%83%E6%95%B8%E8%B7%9F%E6%A8%A1%E6%9D%BF)
=> tag: Add reason parameter for Cleanup

modules/twinkleblock.js, modules/twinkleconfig.js, twinkle.js
=> block: Allow users to opt-in to tag blocked userpage

modules/twinkleblock.js
可以加入`[[Category:…的維基用戶分身]]`語法。
=> block: Add category field to tagging feature

modules/twinkleprotect.js
=> protect: Fix tagging feature with Redirect category shell

modules/twinklexfd.js
=> xfd: Fix nosuchsection in non-wikitext pages

modules/friendlytag.js
Reported at https://w.wiki/3ejB
=> tag: Fix Do not move to Commons_reason

modules/friendlytag.js
From [request on site](https://zh.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=65935561#%E7%BF%BB%E8%AD%AF%E6%A8%A1%E6%9D%BF%E5%8F%83%E6%95%B8)
=> tag: allow up to 3 codes and its status in Expand Language

modules/twinklecopyvio.js, modules/twinklespeedy.js
=> Improve copyvio

modules/twinkleblock.js, morebits.css, morebits.js, scripts/i18n.py, tests/__snapshots__/morebits.quickForm.js.snap
morebits.js
1. 移除 RegExp.escape
block.js
1. block /64
3. 整理 blockPresetsInfo
4. 目前封鎖設定
=> block, morebits: Update from upstream

modules/friendlytalkback.js, modules/twinkleconfig.js
“回复”很 misleading，听起来更像 reply tool
=> 将设置里的回复改为通告

modules/twinklexfd.js
錯誤：<https://zh.wikipedia.org/w/index.php?title=Wikipedia:%E6%94%B6%E9%8C%84%E6%A8%99%E6%BA%96/%E6%8F%90%E5%A0%B1&diff=prev&oldid=86107350>
=> Fix page title not passed into {{Findsources}} if it contains "="

modules/twinkleblock.js
=> block: identify sppUsername in log entry

modules/twinkleclose.js
This reverts commit 8bad8e1fd3881672982928f1a133c3bc079d1fb0.
=> close: Re-enable on vector-2022

twinkle.js
=> fire mw.hook when Twinkle is loaded

modules/friendlytag.js
=> tag: add {{Unreliable sources}}

modules/twinkleblock.js, modules/twinklewarn.js
This should work fine and close #50
=> Check block status change when issuing warning, and vice versa

modules/twinkleblock.js
=> block: add support for action block in partial block
