- modules/twinkleconfig.js
https://github.com/azatoth/twinkle/commit/2728b112f09ac18e49b6e72a8df30e9e2f0abff1
停止支援在使用者子頁面`/Twinkle参数`支援偏好設定，經檢查無人使用
> config: 停止支援使用者子頁面作為偏好設定頁

- morebits.js
Fix #55 
如果頁面中包含重定向，就將其當成重定向，不需要一定在第一行才視為重定向。
例如有人先提交了快速刪除，之後轉交存廢討論就會誤判為請求快速刪除的人為建立者。
> morebits.js: Fix redirect checking regex

- modules/twinkleconfig.js
- modules/twinklefluff.js
https://github.com/azatoth/twinkle/commit/cdc5e3449845f1e176da80455c029fdc68e49cc9
新增在歷史頁面的所有版本添加恢復此版本按鈕。
在最近更改及相關更改的回退按鈕目前已有，不過從en合併以利之後持續更新。
與en不同的是，最近更改和相關更改可以分別啟用。
> fluff: 在歷史頁面添加恢復此版本及合併en版回退

- modules/twinklespeedy.js
> speedy: fix failed to enlarge g11 radio

- modules/twinklearv.js
我沒有用下面upstream來的code，感覺本地沒有那麼複雜。請在review時告知是否可在merge後刪去L786-848和Twinkle.arv.processAN3（unused expression）並移除question。
[已在testwiki測試](https://test.wikipedia.org/wiki/Wikipedia:%E7%AE%A1%E7%90%86%E5%91%98%E9%80%9A%E5%91%8A%E6%9D%BF/3RR)
Fixes #8
> arv: add support to report users to WP:EWIP

- modules/friendlytag.js
https://github.com/azatoth/twinkle/commit/ccc39d3216243219c582f3d9f9cdb2b663261959
News: 當嘗試標記的重定向模板已位於頁面中，且放置在重定向後方而非單獨一行時，Twinkle會加入空的{{Redirect category shell}}，現已修復，會將已存在的模板移動到{{Redirect category shell}}內
> tag: Fix issue in whitespace matching preexisting rcats

- modules/twinkleclose.js
在編輯及刪除摘要中使用章節連結，方便使用者直接連結到對應討論，如同提刪功能的編輯摘要
另外去除頁面標題的底線，其顯示在關閉介面中及編輯摘要
> close: Use anchor link in summary

- modules/twinkleblock.js
Twinkle.block.userIsBot检查IP时会抛出Cannot read property 'map' of undefined TypeError: Cannot read property 'map' of undefined的错误，造成封锁窗口无法展开。
如图：
> block: return false when checking if IP is a bot

- modules/twinkleconfig.js
- modules/twinklestub.js
- twinkle.js
已由更廣泛的disabledModules功能取代
於7/4後再合併
> stub: 移除enableStub偏好設定選項

- modules/twinklefluff.js
- twinkle.js
https://github.com/azatoth/twinkle/commit/14a104830c0d293f44e34a65c1bfc3272030b9b2
Close #94
> fluff: Actually use revertMaxRevisions, ignored for 13 years

- modules/twinklexfd.js
因為模組不可能有重定向，所以不要設定setLookupNonRedirectCreator以免錯誤
Fix #115
> xfd: Don't setLookupNonRedirectCreator for modules

- Gadget.md
- morebits.css
- morebits.js
https://github.com/azatoth/twinkle/commit/f4d70daf941aa29e26c4f9481a2dca1d974ebac2
tooltip的外觀有些變化
> morebits: Remove tipsy dependency, use jQuery UI for tooltips

- modules/twinklefluff.js
Fix bug reported in [WP:VPT](https://zh.wikipedia.org/w/index.php?oldid=60694069#回退功能異常)
And remove unused `intoken`
> fluff: Fix revertToRevID check and remove intoken

- modules/twinklebatchdelete.js
- modules/twinkleprotect.js
- modules/twinklespeedy.js
- modules/twinkleunlink.js
- modules/twinklexfd.js
https://github.com/azatoth/twinkle/commit/40592a44443f7b27d44ccc14866ba9526bebf775
morebits.js 和 twinkle.js 已合併到 master branch，Labels 僅作紀錄
friendlytag.js 在 #121 處理
> Respect WP:LEADORDER when tagging

- maintenance/get_templates.py
- modules/friendlytag.js
https://github.com/azatoth/twinkle/commit/22c57ae6e9e2dbc353a6c957f16665ed01e03ed2
因為無法使用這種語法
```javascript
fileList = {
wgULS('A', 'B'): []
}
```
所以改成
```javascript
fileList = {};
fileList[wgULS('A', 'B')] = [];
```
先前都wgULS整個Object，導致無法自動轉換文字，所以改成這種方式。
> Friendly Tag: Separate file tag data and rendering

- modules/twinkleblock.js
偵測到封鎖衝突時，使用者選擇取消操作，仍然會發出封鎖通知模板，現已修復。
> block: Prevent warning when the block has been changed

- modules/twinkleclose.js
> close: Retag links after page reload

- modules/twinkleclose.js
> close: wrap new del template in ns10 page and improved regex for existing del template

- modules/twinklexfd.js
> 修正XFD「收錄標準」語病

- modules/twinkleblock.js
- modules/twinklewarn.js
> Check block status change when issuing warning, and vice versa

- modules/twinklewarn.js
目前uw-error的界面文字中含有「故意」一詞，違反假定善意；又參考其他警告模板，「故意」一詞在層級3以上也不多使用，故全數移除。
> Remove "deliberately" from uw-error
